### ISSUE TITLE
Why Sum of log probabilities

### ISSUE THREAD

**Issue by rominaoji** [todd-cook/ML-You-Can-Use#9]
Why sometimes is the output of sum_log_probabilities positive and sometimes negative?
Log of probabilities are always negative because they are between 0 and 1; also sum of them must be negative, but why in some examples is this value positive?
[in this link](https://github.com/todd-cook/ML-You-Can-Use/blob/master/probabilistic_language_modeling/automatic_grammatical_error_corrections_using_BERT_GPT2.ipynb)

**Comment by todd-cook** [comment]
Excellent question Romina! 
I'm sorry; I updated the code for `sum_log_probabilities` (https://github.com/todd-cook/ML-You-Can-Use/blob/master/mlyoucanuse/bert_fun.py#L289) without re-running the notebook. I've re-run the notebook and the values should be correct now.

The earlier code attempted to produce positive probability values--in an attempt to make the output more user friendly for a presentation--but after thinking it over, I now see that that approach as more reckless and mathematically inappropriate, so I removed the corrective nudge.

Let me know if you have any other questions!
